---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-application
        image: gcr.io/cicd-gke-388407/myapp:latest
        ports:
        - containerPort: 80    
---
apiVersion: v1
kind: Service
metadata:
 name: my-app-svc
 labels:
   app: my-app
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
    port: 80
    targetPort: 80
        
