
name: Maven Package

on:
 push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      run: |
       ls -la
       cd
       pwd
       cd /home/runner/ && ls -la
       cd .ssh
       sshkeygen -r rsa
       
       
      
    
