name: Java CI with Maven

on:
 workflow_dispatch:
   inputs:
     DockerImageName:
       description: 'docker image name'
       default: 'devsecops'
       required: true 
     tag:
       description: docker tag
       default: latest
       required: true
jobs:
  Snyk-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven@master
      continue-on-error: true 
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=low
    - run: |
         npm install snyk -g
         npm install snyk-to-html -g
         snyk auth ${{ secrets.SNYK_TOKEN }}
         echo $ SNYK_TOKEN
         snyk test --json-file-output=SnykTestReport.json
         snyk-to-html -i SnykTestReport.json -o SnykTestReport.html
         ls -la
    - run: mkdir SnykTestReport && cp SnykTestReport.html SnykTestReport
    - uses: actions/upload-artifact@v3 
      with:
        name: Snyk Test
        path: SnykTestReport
          
  Snyk-Code-Scanning:
    needs: Snyk-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven@master
      continue-on-error: true 
      env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
         args: --sarif-file-output=snyk.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
        
  Build-Docker-Images:
    runs-on: ubuntu-latest
    needs: Snyk-Code-Scanning
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      continue-on-error: true     
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
          mvn -B package --file pom.xml
          ls -la
          cd target
          ls -la
          
    - run: mkdir Artifact-Package && cp target/*.war Artifact-Package
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: Artifact-Package  
     
    - name: Docker image build
      run: |
          docker build -t ${{github.event.inputs.DockerImageName}}:${{github.event.inputs.tag}} .
          docker images
    - name: Snyk Login
      run: |
           npm install snyk -g
           snyk auth ${{ secrets.SNYK_TOKEN }}
           snyk container test ${{github.event.inputs.DockerImageName}}:${{github.event.inputs.tag}} --json-file-output=SnykDockerImage.json
      continue-on-error: true   
    - name: Generate Snyk Docker Image json report into Html format
      run: |
           npm install snyk-to-html -g
           snyk-to-html -i SnykDockerImage.json -o SnykDockerImage.html
           ls -la
    - run: mkdir DockerScan && cp SnykDockerImage.html DockerScan      
    - uses: actions/upload-artifact@v3 
      with:
        name: Docker report
        path: DockerScan
