name: Trivy scan
on:
 workflow_dispatch:
   inputs:
     DockerImageName:
       description: 'docker image name'
       default: 'devsecops'
       required: true 
     tag:
       description: docker tag
       default: latest
       required: true
       
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{github.event.inputs.DockerImageName}}:${{github.event.inputs.tag}} .
          docker images
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{github.event.inputs.DockerImageName}}:${{github.event.inputs.tag}}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
