name: Trivy scan
on:
 workflow_dispatch:
   inputs:
     DockerImageName:
       description: 'docker image name'
       default: 'devsecops'
       required: true 
     tag:
       description: docker tag
       default: latest
       required: true
       
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        continue-on-error: true     
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          cd target
      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{github.event.inputs.DockerImageName}}:${{github.event.inputs.tag}} .
          docker images
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{github.event.inputs.DockerImageName}}:${{github.event.inputs.tag}}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          output: Trivay-Scan.html
          
      - run: mkdir DockerScan && cp Triavy-Scan.html Docker-Image-Scan     
      - uses: actions/upload-artifact@v3 
        with:
         name: Docker Image report
         path: Docker-Image-Scan
