on: [push]

name: Linux_Container Java applicaton

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      continue-on-error: true     
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
          mvn -B package --file pom.xml
          ls -la
          cd target
          ls -la

   # - name: 'Login via Azure CLI'
   #   uses: azure/login@v1
   #   with:
   #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        login-server: myrepo1.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        
        docker build . -t myrepo1.azurecr.io/java-webapp:${{ github.sha }}
        docker images
        docker push myrepo1.azurecr.io/java-webapp:${{ github.sha }} 

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'myjava-webapp1'
        images: 'myrepo1.azurecr.io/java-webapp:${{ github.sha }}'
